# Generated by Django 6.0 on 2025-12-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employeeprofile'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecourseassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeecourseassignment',
            name='company_course_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='courses.companycoursegroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='employeecourseassignment',
            unique_together={('employee', 'course', 'company_course_group')},
        ),
    ]
