# Generated by Django 4.2.25 on 2025-12-24 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Draft"),
                    ("global", "All Companies"),
                    ("specific", "Specific Companies"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="email_templates/"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="CompanyEmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="account.company",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assignments",
                        to="campaigns.emailtemplate",
                    ),
                ),
            ],
            options={"unique_together": {("company", "template")},},
        ),
    ]
