# Generated by Django 6.0 on 2025-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emailtemplate_created_by_emailtemplate_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
