# Generated by Django 6.0 on 2025-12-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_companyemailtemplate_id'),
        ('campaigns', '0004_phishingcampaign_ends_at'),
    ]

    operations = [
    ]
